export let preguntasCine = [
  {
    pregunta: "¿En qué año se estreno Matrix?",
    opcion1: "1997",
    opcion2: "1999",
    opcion3: "2002",
    opcionCorrecta: "1999",
    resuelto: false,
    puntos: 5,
    id: "pc1",
  },
  {
    pregunta: "¿Que actor dio vida a Harry Potter en toda la saga?",
    opcion1: "Elijah Wood",
    opcion2: "Robert Pattinson",
    opcion3: "Daniel Radcliffe",
    opcionCorrecta: "Daniel Radcliffe",
    resuelto: false,
    puntos: 5,
    id: "pc2",
  },
  {
    pregunta: "¿Quién era Jay-Jay?",
    opcion1: "Un Carro",
    opcion2: "Un Avion",
    opcion3: "Un autobus",
    opcionCorrecta: "Un Avion",
    resuelto: false,
    puntos: 5,
    id: "pc3",
  },
  {
    pregunta: "¿Qué fruta es la casa de Bob Esponja?",
    opcion1: "Una Piña",
    opcion2: "Una Manzana",
    opcion3: "Un Mango",
    opcionCorrecta: "Una Piña",
    resuelto: false,
    puntos: 5,
    id: "pc4",
  },
  {
    pregunta: "¿Cuál fue la primera película de Disney?",
    opcion1: "Pinocho",
    opcion2: "La Bella Durmiente",
    opcion3: "Blancanieves",
    opcionCorrecta: "Blancanieves",
    resuelto: false,
    puntos: 5,
    id: "pc5",
  },
  {
    pregunta:
      "¿Cómo se llama el cangrejo de la película ''La sirenita'' de Walt Disney?",
    opcion1: "Santiago",
    opcion2: "Sebastían",
    opcion3: "Serafín",
    opcionCorrecta: "Sebastían",
    resuelto: false,
    puntos: 5,
    id: "pc6",
  },
  {
    pregunta: "¿En qué año se estrenó la película de Disney ''Pinocho''?",
    opcion1: "1990",
    opcion2: "1940",
    opcion3: "1950",
    opcionCorrecta: "1940",
    resuelto: false,
    puntos: 5,
    id: "pc7",
  },
  {
    pregunta: "¿Qué tortuga llevaba el pañuelo azul en ''Las tortugas ninja''?",
    opcion1: "Leonardo",
    opcion2: "Splinter",
    opcion3: "Donatello",
    opcionCorrecta: "Leonardo",
    resuelto: false,
    puntos: 5,
    id: "pc8",
  },
  {
    pregunta: "¿Cómo se llama la hija de Bella Swan en la Saga Crepúsculo?",
    opcion1: "Renee",
    opcion2: "Renesmee",
    opcion3: "Alice",
    opcionCorrecta: "Renesmee",
    resuelto: false,
    puntos: 5,
    id: "pc9",
  },
  {
    pregunta: "¿De cuántas partes se compone la saga de ''El Padrino''?",
    opcion1: "5",
    opcion2: "3",
    opcion3: "7",
    opcionCorrecta: "3",
    resuelto: false,
    puntos: 5,
    id: "pc10",
  },
  {
    pregunta: "¿De qué color era Clifford, el perro gigante?",
    opcion1: "Amarillo",
    opcion2: "Café",
    opcion3: "Rojo",
    opcionCorrecta: "Rojo",
    resuelto: false,
    puntos: 5,
    id: "pc11",
  },
  {
    pregunta: "¿Cómo se llama el primer hijo de Goku de Dragon Ball?",
    opcion1: "Gohan",
    opcion2: "Trunks",
    opcion3: "Goten",
    opcionCorrecta: "Gohan",
    resuelto: false,
    puntos: 5,
    id: "pc12",
  },
];

export let preguntasGeografia = [
  {
    pregunta: "¿Cual es la capital de Brasil?",
    opcion1: "Sao Paulo",
    opcion2: "Rio de Janeiro",
    opcion3: "Brasilia",
    opcionCorrecta: "Brasilia",
    resuelto: false,
    puntos: 5,
    id: "pg1",
  },
  {
    pregunta: "¿En que continente queda Ucrania?",
    opcion1: "Asia",
    opcion2: "Europa",
    opcion3: "Africa",
    opcionCorrecta: "Europa",
    resuelto: false,
    puntos: 5,
    id: "pg2",
  },
  {
    pregunta: "¿Cuál es el área urbana más poblada de la India?",
    opcion1: "Jaipur",
    opcion2: "Bombay",
    opcion3: "Nueva Delhi",
    opcionCorrecta: "Bombay",
    resuelto: false,
    puntos: 5,
    id: "pg3",
  },
  {
    pregunta: "¿A qué isla pertenece la ciudad de Honolulu?",
    opcion1: "Molokai",
    opcion2: "Kauai",
    opcion3: "Hawaii",
    opcionCorrecta: "Hawaii",
    resuelto: false,
    puntos: 5,
    id: "pg4",
  },
  {
    pregunta: "¿En qué país es típico el flamenco?",
    opcion1: "Argentina",
    opcion2: "España",
    opcion3: "Brasil",
    opcionCorrecta: "España",
    resuelto: false,
    puntos: 5,
    id: "pg5",
  },
  {
    pregunta: "¿Cuántas estrellas tiene la bandera de China?",
    opcion1: "6",
    opcion2: "8",
    opcion3: "5",
    opcionCorrecta: "5",
    resuelto: false,
    puntos: 5,
    id: "pg6",
  },
  {
    pregunta: "¿De qué continente es originario el cacao?",
    opcion1: "Asia",
    opcion2: "América",
    opcion3: "Europa",
    opcionCorrecta: "América",
    resuelto: false,
    puntos: 5,
    id: "pg7",
  },
  {
    pregunta: "¿Cuáles son los colores de la bandera de Panamá?",
    opcion1: "Rojo, azul y blanco",
    opcion2: "Amarrillo, azul y rojo",
    opcion3: "Azul, blanco y oro",
    opcionCorrecta: "Rojo, azul y blanco",
    resuelto: false,
    puntos: 5,
    id: "pg8",
  },
  {
    pregunta:
      "¿Cómo se llama el mar donde se ubica Puerto Rico y Rep. Dominicana?",
    opcion1: "Mar Caribe",
    opcion2: "Oceano Atlántico",
    opcion3: "Oceano Pacífico",
    opcionCorrecta: "Mar Caribe",
    resuelto: false,
    puntos: 5,
    id: "pg9",
  },
  {
    pregunta: "¿En qué país se ubica el desierto de Atacama?",
    opcion1: "Perú",
    opcion2: "Chile",
    opcion3: "Ecuador",
    opcionCorrecta: "Chile",
    resuelto: false,
    puntos: 5,
    id: "pg10",
  },
  {
    pregunta: "¿Cuál es el río más caudaloso del mundo?",
    opcion1: "El Orinoco",
    opcion2: "El Amazonas",
    opcion3: "El Panamá",
    opcionCorrecta: "",
    resuelto: false,
    puntos: 5,
    id: "pg11",
  },
  {
    pregunta: "¿De qué país el panda es el animal nacional?",
    opcion1: "Japon",
    opcion2: "Indonesia",
    opcion3: "China",
    opcionCorrecta: "China",
    resuelto: false,
    puntos: 5,
    id: "pg12",
  },
];
